### ISSUE TITLE
Setup issues Maven plugin

### ISSUE THREAD

**Issue by kashipai** [blackducksoftware/hub-maven-plugin#15]
According to the document provided for maven plugin i.e [Confluence](https://blackducksoftware.atlassian.net/wiki/spaces/INTDOCS/pages/47039195/Hub+Maven+Plugin) the user and password have to be configured as hubUserName and hubPassword, or hub.username and hub.password, if we go through the code, that is not so. Could you please sync both code and the documentation. Would be very helpful for people who are setting their projects to be pointing to bdhub

**Comment by psantos1113** [comment]
Thanks for the feedback.  The documentation on Confluence has been updated to remove the incorrect property example.  Only the example with hub.username and hub.password remains in the documentation.
