### ISSUE TITLE
Allow for a flag to ignore Hub related failures and not fail the build

### ISSUE THREAD

**Issue by stavvy-akamen** [blackducksoftware/hub-maven-plugin#5]
@vjkoskela brought up a pull request here:  https://github.com/blackducksoftware/hub-maven-plugin/pull/4

However this should be expanded to handle all potential failure cases for:
- createHubOutput
- deployhHub
- checkPolicy (coming soon)

**Comment by ekerwin** [comment]
The latest release, 1.0.5, has the property 'hub.ignore.failure' which should have the capabilities @vjkoskela is after. If not, please open a new issue and we'll address it.
