### ISSUE TITLE
Version 1.0.5 Breaks Backwards Compatibility

### ISSUE THREAD

**Issue by vjkoskela** [blackducksoftware/hub-maven-plugin#6]
It looks like all the properties have been renamed between version 1.0.4 and 1.0.5 from having dashes (e.g. "hub-password" and "hub-user") to having periods (e.g. "hub.password" and "hub.username") -- in the case of "user" to "username" the property name changes as well.

Further, the documentation still refers to these having dashes:

https://github.com/blackducksoftware/hub-maven-plugin/wiki

I strongly suggest that such breaking changes be indicated by incrementing the project version accordingly (see http://semver.org/); in this case this is an X change. Preferably, such breaking changes should be avoided until a major revision necessitates them; these seem mostly cosmetic.

Here are the new values:

https://github.com/blackducksoftware/hub-maven-plugin/blob/master/src/main/java/com/blackducksoftware/integration/maven/goal/HubMojo.java

Here are the old values:

https://github.com/blackducksoftware/hub-maven-plugin/blob/1.0.4/src/main/java/com/blackducksoftware/integration/maven/PluginConstants.java

Let me know if I've missed something.

**Comment by stavvy-akamen** [comment]
@vjkoskela  Thank you for the feedback!  We wanted to be consistent with the Gradle plugin, but will return the values, deprecate them and provide for backwards compatibility for the next few versions.  I do recommend that you update your settings eventually.

**Comment by vjkoskela** [comment]
Thanks!

My migration path is pretty straight forward, mostly I was concerned about the mismatched documentation and surprise factor that a minor Z-change would break integration completely. It looks like the documentation has been updated.

Just so we are clear, from 1.0.5 onwards the dotted versions will be supported and the recommended configuration? As I said my migration path is simple, but your other clients may have larger install bases.

**Comment by ekerwin** [comment]
We have just released 1.0.6, which has all the new features of 1.0.5, but the old property names should be supported once more. If you find that your config from 1.0.4 still doesn't work, please reopen this or create a new issue so your specific problem can be fixed. Thanks for your feedback and very sorry for any inconvenience this caused!
