### ISSUE TITLE
Exclude certain modules

### ISSUE THREAD

**Issue by bgeveritt** [blackducksoftware/hub-maven-plugin#8]
With multi-module projects, I'd like the ability to exclude certain ones, as I may not want to obtain any information from certain modules that are, for example, only used during development (thus assessing the risk behind these dependencies are unnecessary.)

**Comment by ekerwin** [comment]
This is addressed in 1.3.0 (just released). You can now use 'excludedModules' as a comma-separated list of your project names (artifactIds) and they should be excluded from the output. Please keep these suggestions coming!
