### ISSUE TITLE
There was a problem with one of the scans. Error Status : ERROR_MATCHING

### ISSUE THREAD

**Issue by vjkoskela** [blackducksoftware/hub-maven-plugin#9]
We get the following error on one of our projects:

```
[ERROR] There was an error waiting for the scans: There was a problem with one of the scans. Error Status : ERROR_MATCHING
com.blackducksoftware.integration.hub.exception.HubIntegrationException: There was a problem with one of the scans. Error Status : ERROR_MATCHING
	at com.blackducksoftware.integration.hub.dataservices.scan.ScanStatusDataService.getPendingScans(ScanStatusDataService.java:236)
	at com.blackducksoftware.integration.hub.dataservices.scan.ScanStatusDataService.waitForScansToComplete(ScanStatusDataService.java:161)
	at com.blackducksoftware.integration.hub.dataservices.scan.ScanStatusDataService.assertBomImportScanStartedThenFinished(ScanStatusDataService.java:106)
```

The build still seems to complete successfully:

```
[DEBUG] Starting the Report generation.
[DEBUG] Waiting for the Report to complete.
[DEBUG] Getting the Report content.
[DEBUG] Finished retrieving the Report.
[DEBUG] Cleaning up the Report on the server.
[INFO] Black Duck Hub deploying: com.qualtrics.sujitv:maven-test_bdio.jsonld finished.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:38 min
[INFO] Finished at: 2016-12-13T19:45:03+00:00
[INFO] Final Memory: 51M/809M
[INFO] ------------------------------------------------------------------------
```

This seems related to our upgrade to version 1.2.0, specifically "v 1.2.0, will wait for BOM to be calculated and then create a report" (see https://github.com/blackducksoftware/hub-maven-plugin/wiki/Configuration-and-Setup-for-Hub-Maven-plugin).

This is our configuration as reported by Maven:

```
[DEBUG] Configuring mojo 'com.blackducksoftware.integration:hub-maven-plugin:1.2.0-QTX:deployHubOutput' with basic configurator -->
[DEBUG]   (s) createHubReport = true
[DEBUG]   (s) hubIgnoreFailure = true
[DEBUG]   (s) hubPassword = <REDACTED>
[DEBUG]   (s) hubProjectName = com.qualtrics.sujitv:maven-test
[DEBUG]   (s) hubScanFinishedTimeout = 300
[DEBUG]   (s) hubScanStartedTimeout = 300
[DEBUG]   (s) hubTimeout = 120
[DEBUG]   (s) hubUrl = http://black-duck.service.eng.consul:80
[DEBUG]   (s) hubUsername = automation
[DEBUG]   (s) outputDirectory = /Users/villek/Downloads/sujit/target/blackduck
[DEBUG]   (f) project = MavenProject: com.qualtrics.sujitv:maven-test:1.0.2-SNAPSHOT @ /Users/villek/Downloads/sujit/pom.xml
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@411291e5
[DEBUG] -- end configuration --
```

This is a really simple demo/test project:

```
[villek:sujit (master|✚1…3)]$ find . | grep -v '/\.git/'
.
./.git
./.pom.xml.swp
./my-app
./pom.xml
./settings.xml
./src
./src/main
./src/main/java
./src/main/java/com
./src/main/java/com/mycompany
./src/main/java/com/mycompany/app
./src/main/java/com/mycompany/app/App.java
./src/test
./src/test/java
./src/test/java/com
./src/test/java/com/mycompany
./src/test/java/com/mycompany/app
./src/test/java/com/mycompany/app/AppTest.java
```

Why are we getting this error?

**Comment by ekerwin** [comment]
This is an error reported by the Hub. As this is a demo project, would it be possible for you to share the bdio created with 'mvn com.blackducksoftware.integration:hub-maven-plugin:1.2.0:createHubOutput'? I suspect that we are either generating inaccurate bdio or there is an issue with your Hub server. If I had your bdio, I could attempt to upload it to our Hub servers and further diagnose the issue. If you'd prefer emailing it instead of posting it here, please send it to ekerwin@blackducksoftware.com and I'll get right on it.

**Comment by vjkoskela** [comment]
So I cannot run that goal because the 1.2.0 version of the plugin depends on SNAPSHOTs which are not in Maven Central. It looks like this was fixed with 1.2.1. So:

```
mvn com.blackducksoftware.integration:hub-maven-plugin:1.2.1:createHubOutput
```

(version 1.2.1 not 1.2.0)

I have attached the file that it generates.

[maven-test_bdio.jsonld.zip](https://github.com/blackducksoftware/hub-maven-plugin/files/682892/maven-test_bdio.jsonld.zip)

**Comment by ekerwin** [comment]
I extracted the jsonld file and was able to upload it to our 3.4.0 Hub server and it created a Bill of Materials with one item - junit 3.8.1. Is this not the behavior you are experiencing? Have you tried uploading it directly (click Code Locations in the upper left of the Hub window, then click Add, and select BOM file)?

**Comment by psantos1113** [comment]
Hasn't been any activity on this issue or comments.  Closing this issue as we have released new versions of the plugin since this issue was opened.  If it is still an issue then please re-open with updated comments.
